// DO NOT EDIT — generated by scripts/generate-tts-elevenlabs.mjs.
// Each scene's word-level alignment from the ElevenLabs VO.

export interface CaptionWord {
  word: string;
  /** seconds from VO start */
  start: number;
  /** seconds from VO start */
  end: number;
}

export const captionsBySceneId: Record<number, CaptionWord[]> = {
  "1": [
    {
      "word": "Every",
      "start": 0,
      "end": 0.29
    },
    {
      "word": "day,",
      "start": 0.337,
      "end": 0.58
    },
    {
      "word": "millions",
      "start": 0.697,
      "end": 1.115
    },
    {
      "word": "of",
      "start": 1.149,
      "end": 1.207
    },
    {
      "word": "people",
      "start": 1.254,
      "end": 1.544
    },
    {
      "word": "sign",
      "start": 1.579,
      "end": 1.765
    },
    {
      "word": "transactions",
      "start": 1.8,
      "end": 2.554
    },
    {
      "word": "they",
      "start": 2.601,
      "end": 2.717
    },
    {
      "word": "can't",
      "start": 2.763,
      "end": 3.019
    },
    {
      "word": "actually",
      "start": 3.077,
      "end": 3.437
    },
    {
      "word": "read.",
      "start": 3.518,
      "end": 4.18
    }
  ],
  "2": [
    {
      "word": "Bybit.",
      "start": 0,
      "end": 0.65
    },
    {
      "word": "Radiant.",
      "start": 0.859,
      "end": 1.347
    },
    {
      "word": "Billions,",
      "start": 1.498,
      "end": 2.055
    },
    {
      "word": "lost",
      "start": 2.101,
      "end": 2.368
    },
    {
      "word": "to",
      "start": 2.403,
      "end": 2.45
    },
    {
      "word": "blind",
      "start": 2.496,
      "end": 2.728
    },
    {
      "word": "signing.",
      "start": 2.775,
      "end": 3.437
    }
  ],
  "3": [
    {
      "word": "What",
      "start": 0,
      "end": 0.221
    },
    {
      "word": "if",
      "start": 0.255,
      "end": 0.325
    },
    {
      "word": "your",
      "start": 0.372,
      "end": 0.511
    },
    {
      "word": "wallet",
      "start": 0.604,
      "end": 0.998
    },
    {
      "word": "just",
      "start": 1.057,
      "end": 1.254
    },
    {
      "word": "told",
      "start": 1.3,
      "end": 1.533
    },
    {
      "word": "you",
      "start": 1.579,
      "end": 1.649
    },
    {
      "word": "what",
      "start": 1.683,
      "end": 1.788
    },
    {
      "word": "you're",
      "start": 1.823,
      "end": 1.974
    },
    {
      "word": "about",
      "start": 1.997,
      "end": 2.194
    },
    {
      "word": "to",
      "start": 2.229,
      "end": 2.287
    },
    {
      "word": "do?",
      "start": 2.345,
      "end": 2.926
    }
  ],
  "4": [
    {
      "word": "That's",
      "start": 0,
      "end": 0.279
    },
    {
      "word": "clear",
      "start": 0.337,
      "end": 0.58
    },
    {
      "word": "signing.",
      "start": 0.65,
      "end": 1.149
    },
    {
      "word": "An",
      "start": 1.3,
      "end": 1.44
    },
    {
      "word": "open",
      "start": 1.498,
      "end": 1.718
    },
    {
      "word": "Ethereum",
      "start": 1.765,
      "end": 2.183
    },
    {
      "word": "standard,",
      "start": 2.241,
      "end": 2.682
    },
    {
      "word": "ERC-7730,",
      "start": 2.74,
      "end": 4.865
    },
    {
      "word": "turning",
      "start": 5.248,
      "end": 5.584
    },
    {
      "word": "hex",
      "start": 5.654,
      "end": 5.886
    },
    {
      "word": "into",
      "start": 5.944,
      "end": 6.072
    },
    {
      "word": "plain",
      "start": 6.118,
      "end": 6.339
    },
    {
      "word": "English.",
      "start": 6.397,
      "end": 7.059
    }
  ],
  "5": [
    {
      "word": "Backed",
      "start": 0,
      "end": 0.325
    },
    {
      "word": "by",
      "start": 0.348,
      "end": 0.43
    },
    {
      "word": "the",
      "start": 0.476,
      "end": 0.546
    },
    {
      "word": "Ethereum",
      "start": 0.604,
      "end": 1.022
    },
    {
      "word": "Foundation",
      "start": 1.08,
      "end": 1.602
    },
    {
      "word": "and",
      "start": 1.637,
      "end": 1.707
    },
    {
      "word": "the",
      "start": 1.741,
      "end": 1.811
    },
    {
      "word": "wider",
      "start": 1.846,
      "end": 2.078
    },
    {
      "word": "ecosystem.",
      "start": 2.136,
      "end": 3.065
    }
  ],
  "6": [
    {
      "word": "Clear",
      "start": 0,
      "end": 0.302
    },
    {
      "word": "signing",
      "start": 0.36,
      "end": 0.708
    },
    {
      "word": "is",
      "start": 0.755,
      "end": 0.824
    },
    {
      "word": "live",
      "start": 0.894,
      "end": 1.126
    },
    {
      "word": "in",
      "start": 1.149,
      "end": 1.196
    },
    {
      "word": "WalletChan.",
      "start": 1.254,
      "end": 1.95
    },
    {
      "word": "Every",
      "start": 2.125,
      "end": 2.403
    },
    {
      "word": "dapp.",
      "start": 2.45,
      "end": 2.833
    },
    {
      "word": "Every",
      "start": 2.949,
      "end": 3.181
    },
    {
      "word": "transaction.",
      "start": 3.228,
      "end": 4.365
    }
  ],
  "7": [
    {
      "word": "Finally",
      "start": 0,
      "end": 0.43
    },
    {
      "word": "readable.",
      "start": 0.499,
      "end": 1.207
    }
  ]
};
