#!/bin/bash

# Generate icon sizes from walletchan-icon.png
# Uses sips (macOS built-in) for image resizing

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SOURCE_ICON="$PROJECT_ROOT/public/walletchan-icon.png"
ICONS_DIR="$PROJECT_ROOT/public/icons"

# Icon sizes needed for Chrome extension
SIZES=(16 48 128)

if [ ! -f "$SOURCE_ICON" ]; then
    echo "Error: Source icon not found at $SOURCE_ICON"
    exit 1
fi

mkdir -p "$ICONS_DIR"

for size in "${SIZES[@]}"; do
    output="$ICONS_DIR/icon${size}.png"
    echo "Generating ${size}x${size} icon..."
    sips -z $size $size "$SOURCE_ICON" --out "$output" > /dev/null
done

echo "Done! Icons generated in $ICONS_DIR"
ls -la "$ICONS_DIR"

# EIP-6963 requires the provider icon to be a data: URI or HTTPS URL —
# chrome-extension:// URLs fail spec validators (e.g. RainbowKit). Inline
# a 128x128 PNG of walletchan-icon-white-bg.png as a base64 data URI in
# walletIcon.ts so the inpage bundle can announce it directly. 128px keeps
# the inlined file ~25KB (vs ~1MB for the full-res PNG); the spec only
# requires 96x96 minimum. The animated GIF remains a static asset for
# in-extension UI like ensBanner.
EIP6963_SOURCE="$PROJECT_ROOT/public/walletchan-icon-white-bg.png"
WALLET_ICON_TS="$PROJECT_ROOT/src/chrome/walletIcon.ts"
EIP6963_TMP="$(mktemp -t walletchan-eip6963).png"
trap 'rm -f "$EIP6963_TMP"' EXIT
echo "Generating walletIcon.ts from 128x128 resize of $EIP6963_SOURCE..."
sips -z 128 128 "$EIP6963_SOURCE" --out "$EIP6963_TMP" > /dev/null
{
    echo "// Auto-generated by scripts/generate-icons.sh"
    echo "// Do not edit manually - run the script to update"
    echo ""
    printf 'export const WALLET_ICON = "data:image/png;base64,'
    base64 -i "$EIP6963_TMP" | tr -d '\n'
    echo '";'
} > "$WALLET_ICON_TS"
echo "Wrote $WALLET_ICON_TS ($(wc -c < "$WALLET_ICON_TS") bytes)"
