import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const budgets: Record<string, number> = {
  // This ceiling is lowered after every router extraction. It is intentionally
  // a ratchet, not the end-state target of a small composition root.
  "background.ts": 3_100,

  // Transitional compatibility/coordinator facades.
  "authHandlers.ts": 80,
  "sessionCache.ts": 320,
  "passkeyUnlockCrypto.ts": 60,
  "batchTxHandlers.ts": 1_020,
  "txSimulation.ts": 2_150,
  "batch/batchRequestIntake.ts": 320,
  "batch/batchBankrExecution.ts": 380,
  "batch/batchExecutionRuntime.ts": 20,
  "batch/batchLocalConfirmation.ts": 320,
  "batch/batchSequentialExecution.ts": 360,
  "batch/batchAtomic7702Execution.ts": 350,
  "batch/batchFailure.ts": 80,
  "batch/batchGasEnrichment.ts": 80,
  "simulation/types.ts": 80,
  "simulation/constants.ts": 30,
  "simulation/stateOverrides.ts": 240,
  "simulation/ethSimulateLogs.ts": 140,

  // Focused security implementations must remain independently auditable.
  "background/messageAccessPolicy.ts": 300,
  "background/providerRequestRejection.ts": 140,
  "background/authRouter.ts": 400,
  "background/onboardingRouter.ts": 400,
  "background/accountStateRouter.ts": 400,
  "background/settingsRouter.ts": 400,
  "background/dappPermissionRouter.ts": 400,
  "background/walletConnectSessionRouter.ts": 400,
  "background/watchAssetRouter.ts": 400,
  "background/chainPromptRouter.ts": 400,
  "background/signingRequestRouter.ts": 400,
  "background/transactionStatusRouter.ts": 400,
  "auth/walletUnlock.ts": 220,
  "auth/sessionHydration.ts": 380,
  "auth/legacyVaultKeyMigration.ts": 200,
  "auth/masterPasswordVerification.ts": 120,
  "auth/agentFactorHandlers.ts": 240,
  "auth/bankrCredentialUpdate.ts": 200,
  "auth/masterPasswordRotation.ts": 360,
  "auth/sessionTermination.ts": 60,
  "session/inMemoryCache.ts": 200,
  "session/autoLockPolicy.ts": 100,
  "session/persistence.ts": 220,
  "session/storage.ts": 180,
  "passkey/status.ts": 200,
  "passkey/setup.ts": 360,
  "passkey/hydration.ts": 160,
  "passkey/removal.ts": 120,
  "passkey/record.ts": 200,
  "passkey/keyWrapping.ts": 280,
  "passkey/repository.ts": 60,
  "privateKeyVaultCrypto.ts": 150,
  "vaultCrypto.ts": 340,
  "mnemonicStorage.ts": 80,
  "mnemonic/derivation.ts": 90,
  "mnemonic/masterAccess.ts": 150,
  "mnemonic/integrity.ts": 120,
  "mnemonic/addressPreview.ts": 130,
  "mnemonic/accountPersistence.ts": 220,
  "mnemonic/accountHandlers.ts": 320,
  "mnemonic/record.ts": 180,
  "mnemonic/crypto.ts": 230,
  "mnemonic/repository.ts": 60,
  "mnemonic/operations.ts": 220,
  "mnemonic/recovery.ts": 280,
  "accountStorage.ts": 80,
  "accounts/authorization.ts": 40,
  "accounts/repository.ts": 180,
  "accounts/selectionStorage.ts": 200,
  "accounts/bankrStorage.ts": 200,
  "accounts/localStorage.ts": 160,
  "accounts/seedStorage.ts": 140,
  "accounts/seedGroupStorage.ts": 120,
  "onboardingInitialization.ts": 40,
  "onboardingInitializationState.ts": 230,
  "onboardingInitializationLifecycle.ts": 220,
  "onboardingCredentialInitialization.ts": 130,
  "localSigner.ts": 50,
  "localSigning/types.ts": 80,
  "localSigning/client.ts": 90,
  "localSigning/transactionBroadcast.ts": 150,
  "localSigning/transactionSigner.ts": 150,
  "localSigning/messageSigner.ts": 150,
  "localSigning/privateKey.ts": 40,
  "eip712Validator.ts": 140,
  "eip712ValidationTypes.ts": 30,
  "eip712DelegationPolicy.ts": 80,
  "eip712SchemaValidation.ts": 220,
  "eip712Sanitization.ts": 80,
  "erc7715PermissionHandlers.ts": 50,
  "erc7715/methods.ts": 80,
  "erc7715/onchainStatus.ts": 190,
  "erc7715/queries.ts": 60,
  "erc7715/grantSnapshot.ts": 100,
  "erc7715/revocation.ts": 180,
  "erc7715/confirmation.ts": 260,
  "erc7715/requestHandler.ts": 150,
  "pendingErc7715PermissionStorage.ts": 60,
  "erc7715/types.ts": 140,
  "erc7715/permissionBadge.ts": 20,
  "erc7715/pendingRequestStorage.ts": 100,
  "erc7715/grantStorage.ts": 180,
  "erc7715/resultStorage.ts": 120,
  "erc7715/expiry.ts": 80,
  "erc7715/address.ts": 40,
  "erc7715/grantBoundary.ts": 80,
  "erc7715/resolution.ts": 80,
  "erc7715/requestLock.ts": 100,
  "erc7715/delegationSigning.ts": 320,
  "erc7715/registry.ts": 30,
  "erc7715/permissionTypes.ts": 50,
  "erc7715/validationPrimitives.ts": 150,
  "erc7715/ruleValidation.ts": 90,
  "erc7715/permissionValidation.ts": 340,
  "erc7715/caveats.ts": 30,
  "erc7715/caveatDefinitions.ts": 60,
  "erc7715/caveatEncoding.ts": 250,
  "erc7715/caveatBuilder.ts": 270,
  "erc7715/preflight.ts": 30,
  "erc7715/preflightNormalization.ts": 170,
  "erc7715/preflightRpc.ts": 110,
  "erc7715/preflightEligibility.ts": 210,
  "erc7715/pendingPermissionRequest.ts": 80,
  "batch/batchTxEncoding.ts": 220,
  "batch/batchRequestStatusHandlers.ts": 180,
};

test("refactored security modules stay within ratcheting audit budgets", async () => {
  for (const [name, maximumLines] of Object.entries(budgets)) {
    const source = await readFile(
      new URL(`../../src/chrome/${name}`, import.meta.url),
      "utf8",
    );
    const lines = source.split("\n").length;
    assert.ok(
      lines <= maximumLines,
      `${name} has ${lines} lines; audit budget is ${maximumLines}`,
    );
  }
});
