/**
 * Bankr API client for transaction submission, message signing, and job polling
 */

import { BANKR_API_BASE } from "@/constants/externalUrls";
import {
  recoverMessageAddress,
  recoverTypedDataAddress,
  type Hex,
} from "viem";
import {
  fetchTextBounded,
  HttpRequestTimeoutError,
  HttpResponseTooLargeError,
} from "./boundedHttpResponse";
import {
  BankrApiError,
  extractBankrErrorMessage,
  isEvmAddress,
  normalizeJobStatus,
  normalizeSignMessageResponse,
  normalizeSubmitTransactionResponse,
  type JobStatus,
  type SignMessageResponse,
  type SubmitTransactionDirectResponse,
} from "./bankrApiResponse";
import {
  WALLET_SECRET_OPERATION_LOCK_KEY,
  withStorageLock,
} from "./storageLock";

export {
  BankrApiError,
  type JobStatus,
  type SignMessageResponse,
  type SubmitTransactionDirectResponse,
} from "./bankrApiResponse";

const API_BASE_URL = BANKR_API_BASE;
const BANKR_SIGNER_TIMEOUT_MS = 45_000;
const BANKR_JOB_TIMEOUT_MS = 30_000;
const BANKR_RESPONSE_MAX_BYTES = 256 * 1024;
const BANKR_JOB_RESPONSE_MAX_BYTES = 512 * 1024;

export interface TransactionParams {
  from: string;
  to: string | null;
  data?: string;
  value?: string;
  chainId: number;
  gas?: string;
  gasPrice?: string;
  maxFeePerGas?: string;
  maxPriorityFeePerGas?: string;
}

async function bankrFetchText(
  path: string,
  init: RequestInit,
  options: { timeoutMs?: number; maxBytes?: number; action: string },
): Promise<{ response: Response; text: string }> {
  try {
    return await fetchTextBounded(
      `${API_BASE_URL}${path}`,
      { ...init, redirect: "error" },
      {
        timeoutMs: options.timeoutMs ?? BANKR_SIGNER_TIMEOUT_MS,
        maxBytes: options.maxBytes ?? BANKR_RESPONSE_MAX_BYTES,
      },
    );
  } catch (error) {
    if (error instanceof HttpRequestTimeoutError) {
      throw new BankrApiError(`Bankr ${options.action} timed out`);
    }
    if (error instanceof HttpResponseTooLargeError) {
      throw new BankrApiError(
        `Bankr returned an oversized ${options.action} response`,
      );
    }
    throw error;
  }
}

/**
 * Submits a transaction directly via /wallet/submit (synchronous, no polling)
 */
export async function submitTransactionDirect(
  apiKey: string,
  tx: TransactionParams,
  signal?: AbortSignal,
  beforeIrreversibleRequest?: () => void | Promise<void>,
): Promise<SubmitTransactionDirectResponse> {
  if (!isEvmAddress(tx.from)) {
    throw new BankrApiError("Transaction is missing a valid reviewed signer");
  }

  // `/wallet/submit` does not accept `from`. Prove the global API credential
  // controls the reviewed account before invoking the irreversible endpoint.
  // This protects both newly verified credentials and legacy installations.
  await verifyBankrCredentialAddress(apiKey, tx.from, signal);

  // Bankr's /wallet/submit schema rejects any non-whitelisted key in
  // `params.transaction` (zod `unrecognized_keys`). Bankr handles gas
  // server-side, so we only forward to/value/data/chainId here. Any
  // `tx.gas` / `tx.gasPrice` / `tx.maxFeePerGas` / `tx.maxPriorityFeePerGas`
  // fields on the pending tx (from the dapp, our local sim, or the user's
  // tier picker) are intentionally dropped on this path — they only apply
  // to local-signing accounts (PK/Seed).
  const body: Record<string, any> = {
    transaction: {
      to: tx.to || undefined,
      chainId: tx.chainId,
      value: hexToDecimalString(tx.value),
      data: tx.data && tx.data !== "0x" ? tx.data : undefined,
    },
    waitForConfirmation: true,
  };

  // Remove undefined fields from transaction
  body.transaction = Object.fromEntries(
    Object.entries(body.transaction).filter(([, v]) => v !== undefined)
  );

  let response: Response;
  let text: string;
  let request: Promise<{ response: Response; text: string }> | null = null;
  let irreversibleStarted = false;
  try {
    await withStorageLock(WALLET_SECRET_OPERATION_LOCK_KEY, async () => {
      await beforeIrreversibleRequest?.();
      irreversibleStarted = true;
      request = bankrFetchText(
        "/wallet/submit",
        {
          method: "POST",
          headers: {
            "X-API-Key": apiKey,
            "Content-Type": "application/json",
          },
          body: JSON.stringify(body),
          signal,
        },
        { action: "transaction submission" },
      );
    });
    if (!request) throw new Error("Bankr submission did not start");
    ({ response, text } = await request);
  } catch (error) {
    if (!irreversibleStarted) throw error;
    throw new BankrApiError(
      "Transaction submission outcome is unknown; check activity before retrying.",
      undefined,
      true,
    );
  }

  if (!response.ok) {
    // A timeout/rate-limit/conflict can be generated by a proxy after the
    // upstream signer accepted the POST. Treat those statuses like 5xx: the
    // user must reconcile activity instead of creating a second intent.
    if (
      response.status === 408 ||
      response.status === 409 ||
      response.status === 425 ||
      response.status === 429 ||
      response.status >= 500
    ) {
      throw new BankrApiError(
        "Transaction submission outcome is unknown; check activity before retrying.",
        response.status,
        true,
      );
    }
    throw new BankrApiError(
      `Failed to submit transaction: ${extractBankrErrorMessage(text)}`,
      response.status
    );
  }

  let payload: unknown;
  try {
    payload = JSON.parse(text);
  } catch {
    throw new BankrApiError(
      "Bankr response could not prove the transaction outcome; check activity before retrying.",
      undefined,
      true,
    );
  }
  try {
    return normalizeSubmitTransactionResponse(
      payload,
      tx.from,
      tx.chainId,
    );
  } catch (error) {
    if (error instanceof BankrApiError) {
      throw new BankrApiError(
        `${error.message}. Check activity before retrying.`,
        error.statusCode,
        true,
      );
    }
    throw error;
  }
}

/**
 * Signs a message or typed data via /wallet/sign (synchronous)
 */
export async function signMessageViaApi(
  apiKey: string,
  method: string,
  params: any[],
  signal?: AbortSignal
): Promise<SignMessageResponse> {
  let body: Record<string, any>;
  let expectedSigner: unknown;

  if (method === "personal_sign") {
    // params[0] is hex message, params[1] is address
    const hexMsg = params[0];
    let message = hexMsg;
    // Decode hex to UTF-8 string for the API
    if (typeof hexMsg === "string" && hexMsg.startsWith("0x")) {
      try {
        const hex = hexMsg.slice(2);
        const bytes = new Uint8Array(
          hex.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
        );
        message = new TextDecoder().decode(bytes);
      } catch {
        message = hexMsg;
      }
    }
    body = { signatureType: "personal_sign", message };
    expectedSigner = params[1];
  } else if (method === "eth_sign") {
    // SECURITY: eth_sign signs an untyped raw digest and must stay rejected at
    // intake. Keep the old mapping visible as a reminder not to re-enable it.
    // params[0] is address, params[1] is the data hash.
    // body = { signatureType: "personal_sign", message: params[1] };
    throw new BankrApiError(
      "eth_sign is deprecated and unsafe; use personal_sign or eth_signTypedData_v4"
    );
  } else if (method.startsWith("eth_signTypedData")) {
    // params[0] is address, params[1] is typed data (may be stringified JSON)
    let typedData = params[1];
    if (typeof typedData === "string") {
      typedData = JSON.parse(typedData);
    }
    body = { signatureType: "eth_signTypedData_v4", typedData };
    expectedSigner = params[0];
  } else {
    throw new BankrApiError(`Unsupported signing method: ${method}`);
  }

  if (!isEvmAddress(expectedSigner)) {
    throw new BankrApiError("Signing request is missing a valid signer address");
  }

  const { response, text } = await bankrFetchText(
    "/wallet/sign",
    {
      method: "POST",
      headers: {
        "X-API-Key": apiKey,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
      signal,
    },
    { action: "signature" },
  );

  if (!response.ok) {
    throw new BankrApiError(extractBankrErrorMessage(text), response.status);
  }

  let payload: unknown;
  try {
    payload = JSON.parse(text);
  } catch {
    throw new BankrApiError("Bankr returned invalid JSON for signature");
  }
  const result = normalizeSignMessageResponse(
    payload,
    expectedSigner,
    body.signatureType,
  );
  let recoveredSigner: string;
  try {
    recoveredSigner =
      body.signatureType === "personal_sign"
        ? await recoverMessageAddress({
            message: body.message,
            signature: result.signature as Hex,
          })
        : await recoverTypedDataAddress({
            ...(body.typedData as Parameters<
              typeof recoverTypedDataAddress
            >[0]),
            signature: result.signature as Hex,
          });
  } catch {
    throw new BankrApiError(
      "Bankr returned a signature that could not be verified",
    );
  }
  if (recoveredSigner.toLowerCase() !== expectedSigner.toLowerCase()) {
    throw new BankrApiError(
      "Bankr signature does not belong to the reviewed account",
    );
  }
  return result;
}

/** Verify a Bankr API key/account pair without creating an onchain effect. */
export async function verifyBankrCredentialAddress(
  apiKey: string,
  address: string,
  signal?: AbortSignal,
): Promise<void> {
  if (!isEvmAddress(address)) {
    throw new BankrApiError("Invalid Bankr account address");
  }
  const challenge = `WalletChan Bankr account verification:${address.toLowerCase()}`;
  const challengeHex = `0x${Array.from(
    new TextEncoder().encode(challenge),
    (byte) => byte.toString(16).padStart(2, "0"),
  ).join("")}`;
  await signMessageViaApi(
    apiKey,
    "personal_sign",
    [challengeHex, address],
    signal,
  );
}

/**
 * Polls the job status from the Bankr API
 */
export async function getJobStatus(
  apiKey: string,
  jobId: string,
  signal?: AbortSignal
): Promise<JobStatus> {
  if (!/^[A-Za-z0-9_-]{1,256}$/.test(jobId)) {
    throw new BankrApiError("Invalid Bankr job ID");
  }
  const { response, text } = await bankrFetchText(
    `/agent/job/${jobId}`,
    {
      method: "GET",
      headers: { "X-API-Key": apiKey },
      signal,
    },
    {
      action: "job status",
      timeoutMs: BANKR_JOB_TIMEOUT_MS,
      maxBytes: BANKR_JOB_RESPONSE_MAX_BYTES,
    },
  );

  if (!response.ok) {
    throw new BankrApiError(
      `Failed to get job status: ${extractBankrErrorMessage(text)}`,
      response.status,
    );
  }

  let payload: unknown;
  try {
    payload = JSON.parse(text);
  } catch {
    throw new BankrApiError("Bankr returned invalid JSON for job status");
  }
  return normalizeJobStatus(payload);
}

/**
 * Polls job status until completion or timeout
 */
export async function pollJobUntilComplete(
  apiKey: string,
  jobId: string,
  options: {
    pollInterval?: number; // ms
    maxDuration?: number; // ms
    onStatusUpdate?: (status: JobStatus) => void;
    signal?: AbortSignal;
  } = {}
): Promise<JobStatus> {
  const { pollInterval = 2000, maxDuration = 300000, onStatusUpdate, signal } = options;

  const startTime = Date.now();

  while (Date.now() - startTime < maxDuration) {
    // Check if cancelled
    if (signal?.aborted) {
      throw new DOMException("Transaction cancelled", "AbortError");
    }

    const status = await getJobStatus(apiKey, jobId, signal);

    if (onStatusUpdate) {
      onStatusUpdate(status);
    }

    if (status.status === "completed" || status.status === "failed") {
      return status;
    }

    await sleep(pollInterval, signal);
  }

  throw new BankrApiError("Transaction timeout: exceeded maximum wait time");
}

/**
 * Converts hex value to decimal string (wei)
 */
function hexToDecimalString(hex: string | undefined): string {
  if (!hex || hex === "0x0" || hex === "0x") {
    return "0";
  }
  try {
    return BigInt(hex).toString();
  } catch {
    return "0";
  }
}

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(signal.reason ?? new DOMException("Cancelled", "AbortError"));
      return;
    }
    const timer = setTimeout(() => {
      signal?.removeEventListener("abort", abort);
      resolve();
    }, ms);
    const abort = () => {
      clearTimeout(timer);
      reject(signal?.reason ?? new DOMException("Cancelled", "AbortError"));
    };
    signal?.addEventListener("abort", abort, { once: true });
  });
}
