export const PRIVACY_WALLET_UI_MESSAGE_TYPES = [
  "privacyEnsureInitialized",
  "privacyRunShieldReadinessCheck",
  "privacyRunProverSelfTest",
  "privacyQuoteShield",
  "privacyPrepareShieldReview",
  "privacyPrepareShield",
  "privacyListShieldOperations",
  "privacySyncShield",
  "privacyPrepareUnshieldQuote",
  "privacyExecuteUnshield",
  "privacyPrepareDirectUnshield",
  "privacyPreviewRagequit",
  "privacyPrepareRagequit",
  "privacyPrepareRagequitBatch",
  "privacyGetRecoveryStatus",
  "privacyRevealRecovery",
  "privacyRestoreRecovery",
  "privacyRescanRecovery",
  "privacyGetResetRisk",
] as const;
